### ISSUE TITLE
Remove framed compact drawers dependancy 

### ISSUE THREAD

**Issue by ThePansmith** [MaxNeedsSnacks/FramingTemplates#1]
Attempting to load the mod without FCD will give a noclassdeffound error.

**Comment by MaxNeedsSnacks** [comment]
Can you give the stacktrace of one of those errors? Everything *should* have been compartmentalised correctly, but maybe I call SD code somewhere I shouldn't be

**Comment by MaxNeedsSnacks** [comment]
Nevermind, it's contrived classloading bullshit...

Here's the new file, still under review but should fix your issue ^^;
https://legacy.curseforge.com/minecraft/mc-mods/framing-templates/files/5615934
